### PR TITLE
refactor: use `@nuxt/ui` for examples

### LINKED ISSUE #59: docs example stackblitz projects are missing components
### Environment

docs

### Reproduction

https://nuxt.com/docs/examples/advanced/use-cookie

### Describe the bug

Components like `NuxtExampleLayout` and others like `NButton` can't be resolved leaving a pretty much unstyled page 

### Additional context

_No response_

### Logs

```shell-script
ue warn]: Failed to resolve component: NuxtExampleLayout
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: NTip
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: NButton
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: NTextInput
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.
[Vue warn]: Failed to resolve component: NuxtExampleLayout
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: NTip
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: NButton
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: NTextInput
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render functio
```

### PR DESCRIPTION
**Pull request by arashsheyda**
refactored the code from old `@nuxt/devtools-ui` to `@nuxt/ui`

- moved all the examples udner a sub directory called `examples` (the goal was to have a cleaner directory structure, if it's not a good idea we can revert that)
- add `@nuxt/examples-ui` for shared ui usages udner `shared` directory
- currently, `auth` is not in `.docs`, should we add that?

`NuxtLayoutExample` looks like this: (I can record all the examples if needed to see how they look like)

https://github.com/nuxt/examples/assets/38922203/069b5e0c-1a57-44da-8118-08e7e9153f59

resolves #59

### CODE REVIEW

**Comment by arashsheyda** [comment]
also rn the examples are using the shared ui (`@nuxt/examples-ui`) like this, would this work on stackblitz?

```
  "devDependencies": {
    "@nuxt/examples-ui": "workspace:*",
    "nuxt": "^3.8.1"
  }
```

**Comment by Atinux** [comment]
I think I will have to publish on npm the package @arashsheyda

**Comment by arashsheyda** [comment]
okay thanks :D

**Comment by Atinux** [comment]
https://www.npmjs.com/package/@nuxt/examples-ui

**Review by danielroe — APPROVED** [review]
Should be good to go - see https://examples-6makfan46-nuxt-js.vercel.app/?force=local-auth for example.

**Comment by danielroe** [comment]
(One note: we may need to update the e2e tests...)

**Comment by danielroe** [comment]
let's merge https://github.com/nuxt/examples/pull/45 first (I'll finish it off) and then confirm all working with this PR

**Pull request merged**
